title: Cayman Blog Theme
description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and Gitlab/GitHub Pages.
show_downloads: true

baseurl: "/hello-world" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://leipelt.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# hello-world date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hello-world:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: leipelt
image: /thumbnail-jumbo.png
twitter:
  username: leipelt

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
